"""Generate the sixteen liquid volumes from cavity dimensions and a linear fill scale."""
import json
import hashlib
import copy
import struct
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DESTINATION = ROOT / 'src/main/resources/craftengine/farmersdelight_fluids/resourcepack/assets/farmersdelight/models/block/jug_fluid'

def legacy_model(shell, liquid):
    """Flatten the two existing meshes for clients without composite item models."""
    merged = copy.deepcopy(shell)
    merged['ambientocclusion'] = False
    merged['textures']['legacy_liquid'] = 'farmersdelight:block/jug_legacy_liquid'
    volume = copy.deepcopy(liquid['elements'])
    for element in volume:
        for face in element['faces'].values():
            face['texture'] = '#legacy_liquid'
            face.pop('tintindex', None)
    merged['elements'].extend(volume)
    return merged

def legacy_texture():
    """Author a small fixed blue wave tile; no external pixels are read or copied."""
    def chunk(kind, data):
        return struct.pack('>I', len(data)) + kind + data + struct.pack('>I', zlib.crc32(kind + data) & 0xffffffff)
    rows = bytearray()
    for y in range(16):
        rows.append(0)
        for x in range(16):
            wave = (x + 2 * y) % 8
            bright = 12 if wave == 0 else (5 if wave == 1 else 0)
            rows.extend((54 + bright, 103 + bright, 205 + bright, 255))
    return (b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', 16, 16, 8, 6, 0, 0, 0))
            + chunk(b'IDAT', zlib.compress(bytes(rows), 9)) + chunk(b'IEND', b''))

def model(level):
    height = round(1.125 + 10.5 * level / 16, 6)
    return {
        'parent': 'minecraft:block/block',
        'ambientocclusion': False,
        'textures': {'particle': 'minecraft:block/water_still', 'liquid': 'minecraft:block/water_still'},
        'elements': [{
            'from': [4.125, 1.125, 4.125], 'to': [11.875, height, 11.875],
            'shade': False,
            'faces': {face: {'uv': [0, 0, 16, 16], 'texture': '#liquid', 'tintindex': 1}
                      for face in ('down', 'up', 'north', 'south', 'west', 'east')}
        }]
    }

if __name__ == '__main__':
    DESTINATION.mkdir(parents=True, exist_ok=True)
    for level in range(1, 17):
        target = DESTINATION / f'glass_jug_fluid_model_{level:02}.json'
        target.write_text(json.dumps(model(level), ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    shell_path = DESTINATION.parent / 'glass_jug.json'
    shell = json.loads(shell_path.read_text(encoding='utf-8'))
    for element in shell.get('elements', []):
        for face in element.get('faces', {}).values():
            face['tintindex'] = 0
    derived = DESTINATION.parent / 'glass_jug_tinted.json'
    derived.write_text(json.dumps(shell, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    invisible = DESTINATION.parent / 'fluid_tank_invisible.json'
    invisible.write_text(json.dumps({
        'parent': 'minecraft:block/block',
        'textures': {'particle': 'farmersdelight:block/jug_side'},
        'elements': []
    }, indent=2) + '\n', encoding='utf-8')
    pack = ROOT / 'src/main/resources/craftengine/farmersdelight_fluids'
    manifest_file = pack / 'ASSET-ORIGINS.json'
    manifest = json.loads(manifest_file.read_text(encoding='utf-8'))
    asset_root = pack / 'resourcepack/assets/farmersdelight'
    legacy_directory = DESTINATION.parent / 'jug_legacy'
    legacy_directory.mkdir(parents=True, exist_ok=True)
    legacy_files = []
    for shell_name in ('glass_jug', 'jug'):
        source_path = DESTINATION.parent / f'{shell_name}.json'
        original = json.loads(source_path.read_text(encoding='utf-8'))
        for level in range(1, 17):
            target = legacy_directory / f'{shell_name}_level_{level:02}.json'
            target.write_text(json.dumps(legacy_model(original, model(level)), ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
            legacy_files.append({
                'path': target.relative_to(asset_root).as_posix(),
                'sha256': hashlib.sha256(target.read_bytes()).hexdigest(),
                'sources': [source_path.relative_to(asset_root).as_posix(),
                            f'models/block/jug_fluid/glass_jug_fluid_model_{level:02}.json']})
    texture = asset_root / 'textures/block/jug_legacy_liquid.png'
    texture.write_bytes(legacy_texture())
    manifest['generated_legacy_models'] = {
        'generator': 'tools/generate-tank-liquid-models.py',
        'license': 'AGPL-3.0-only',
        'upstream_geometry': {
            'commit': manifest['commit'], 'license': 'MIT', 'copyright': manifest['copyright'],
            'description': 'Shell meshes and textures retain their original MIT attribution; liquid meshes are generated by this project.'},
        'files': legacy_files}
    manifest['generated_legacy_textures'] = {
        'generator': 'tools/generate-tank-liquid-models.py', 'license': 'AGPL-3.0-only',
        'description': 'Original fixed blue wave tile for pre-1.21.4 clients without dynamic RGB item model tints.',
        'files': [{'path': texture.relative_to(asset_root).as_posix(),
                   'sha256': hashlib.sha256(texture.read_bytes()).hexdigest()}]}
    for entry in manifest['generated_liquid_models']['files']:
        entry['sha256'] = hashlib.sha256((asset_root / entry['path']).read_bytes()).hexdigest()
    manifest['derived'] = [{
        'path': str(derived.relative_to(asset_root)).replace('\\', '/'),
        'sha256': hashlib.sha256(derived.read_bytes()).hexdigest(),
        'source': 'models/block/glass_jug.json',
        'upstream_commit': manifest['commit'], 'license': 'MIT',
        'change': 'Add glass tint index 0 to upstream faces; original geometry and textures remain attributed to vectorwing.'
    }]
    manifest['generated_auxiliary_models'] = [{
        'path': str(invisible.relative_to(asset_root)).replace('\\', '/'),
        'sha256': hashlib.sha256(invisible.read_bytes()).hexdigest(),
        'generator': 'tools/generate-tank-liquid-models.py',
        'description': 'Empty waterlogged base; instance shell and liquid are rendered by dynamic item displays.'
    }]
    manifest_file.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
